// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpzuywxkuchvrtrnazji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwenV5d3hrdWNodnJ0cm5hemppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODY4MzcsImV4cCI6MjA3NDU2MjgzN30.yWN3lPmF2fX6POH3tGNUi9JE2uY7mN1TbSZegVMN0f8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});